element_create:
    path:     /element/create
    defaults: { _controller: CoreBundle:ApiElement:create }
    requirements:
        _method: POST

element_update:
    path:     /element/update
    defaults: { _controller: CoreBundle:ApiElement:update }
    requirements:
        _method: POST

element_delete:
    path:     /element/delete
    defaults: { _controller: CoreBundle:ApiElement:delete }
    requirements:
        _method: POST

element_share:
    path:     /element/share
    defaults: { _controller: CoreBundle:ApiElement:share }
    requirements:
        _method: POST

element_visible:
    path:     /element/visible
    defaults: { _controller: CoreBundle:ApiElement:visible }
    requirements:
        _method: POST

element_refresh_date:
    path:     /element/refreshdate
    defaults: { _controller: CoreBundle:ApiElement:refreshDate }
    requirements:
        _method: POST

element_all:
    path:     /category/{idCat}/town/{idTown}/elements/{limit}
    defaults: { _controller: CoreBundle:ApiElement:allElement }
    requirements:
        _method: GET

element_all_by_user:
    path:     /elements/{type}/user/{idUser}/{limit}
    defaults: { _controller: CoreBundle:ApiElement:allElementByUser }
    requirements:
        _method: GET

request_all:
    path:     /requests/{idTown}/{limit}
    defaults: { _controller: CoreBundle:ApiElement:allRequest }
    requirements:
        _method: GET

offer_all:
    path:     /offers/{idTown}/{limit}
    defaults: { _controller: CoreBundle:ApiElement:allOffer }
    requirements:
        _method: GET