core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

app_user:
    resource: "@AppUserBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#APIs
2bm_api_country:
    type: rest
    resource: "@CoreBundle/Resources/config/routing_api_country.yml"
    prefix:   /api/

2bm_api_categorie:
    type: rest
    resource: "@CoreBundle/Resources/config/routing_api_categorie.yml"
    prefix:   /api/

2bm_api_client:
    type: rest
    resource: "@CoreBundle/Resources/config/routing_api_client.yml"
    prefix:   /api/

2bm_api_element:
    type: rest
    resource: "@CoreBundle/Resources/config/routing_api_element.yml"
    prefix:   /api/

2bm_api_commentaire:
    type: rest
    resource: "@CoreBundle/Resources/config/routing_api_commentaire.yml"
    prefix:   /api/