<?php

namespace CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends EntityRepository
{
    public function findAllByElement($idElement, $limit)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT c
            FROM CoreBundle:Commentaire c
            JOIN c.element e
            WHERE e.id = :idElement
            ORDER BY c.dateCreation DESC 
        ')->setParameters(array(
            'idElement' => $idElement
        ));
        return $query
            ->setMaxResults($limit)
            ->getResult();
    }
}
