<?php

namespace CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementRepository extends EntityRepository
{

    public function findAllElement($idTown) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT e
            FROM CoreBundle:Element e
            JOIN e.utilisateur u
            JOIN u.town t
            WHERE t.id = :idTown Order by e.dateCreation DESC
        ')->setParameters( array (
            'idTown' => $idTown
        ));

        return $query->getResult();
    }
}
