<?php

namespace CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementRepository extends EntityRepository
{

    public function findAllElement($idTown, $limit) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT e
            FROM CoreBundle:Element e
            JOIN e.utilisateur u
            JOIN u.town t
            WHERE t.id = :idTown Order by e.dateCreation DESC
        ')->setParameters( array (
            'idTown' => $idTown
        ));

        return $query
            ->setMaxResults($limit)
            ->getResult();
    }

    public function findAllRequest($idTown, $limit) {
        $param = "Request";
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT e
            FROM CoreBundle:Element e
            JOIN e.utilisateur u
            JOIN e.categorie c
            JOIN u.town t
            WHERE t.id = :idTown 
            AND c.libelle = :param
            Order by e.dateCreation DESC
        ')->setParameters( array (
            'idTown' => $idTown,
            'param' => $param
        ));

        return $query
            ->setMaxResults($limit)
            ->getResult();
    }

    public function findAllOffer($idTown, $limit) {
        $param = "Offer";
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT e
            FROM CoreBundle:Element e
            JOIN e.utilisateur u
            JOIN e.categorie c
            JOIN u.town t
            WHERE t.id = :idTown 
            AND c.libelle = :param
            Order by e.dateCreation DESC
        ')->setParameters( array (
            'idTown' => $idTown,
            'param' => $param
        ));

        return $query
            ->setMaxResults($limit)
            ->getResult();
    }

    public function findAllElementByUser($idUser, $categorie, $limit) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT e
            FROM CoreBundle:Element e
            JOIN e.utilisateur u
            JOIN e.categorie c
            WHERE u.id = :idUser 
            AND c.libelle = :categorie
            Order by e.dateCreation DESC
        ')->setParameters( array (
            'idUser' => $idUser,
            'categorie' => $categorie
        ));

        return $query
            ->setMaxResults($limit)
            ->getResult();
    }
}
