<?php

namespace CoreBundle\Repository;

/**
 * RepportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepportRepository extends \Doctrine\ORM\EntityRepository
{
}
